"""empty message

Revision ID: 13356f5ceeb4
Revises: 7ad45aa99140
Create Date: 2024-11-28 08:07:58.445627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13356f5ceeb4'
down_revision: Union[str, None] = '7ad45aa99140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('question', sa.Text(), nullable=True))
    op.drop_column('messages', 'queation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('queation', mysql.TEXT(), nullable=True))
    op.drop_column('messages', 'question')
    # ### end Alembic commands ###
