"""student record field add text_data

Revision ID: 6d460a190c1a
Revises: 602f23bdfa95
Create Date: 2024-12-04 20:27:37.542978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d460a190c1a'
down_revision: Union[str, None] = '602f23bdfa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_records', sa.Column('text_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_records', 'text_data')
    # ### end Alembic commands ###
