"""Change text_data to JSON type

Revision ID: 813ba25d6784
Revises: 6d460a190c1a
Create Date: 2024-12-05 02:04:23.769031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '813ba25d6784'
down_revision: Union[str, None] = '6d460a190c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_records', 'text_data',
               existing_type=mysql.TEXT(),
               type_=mysql.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_records', 'text_data',
               existing_type=mysql.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
