"""Add deleted_at for soft delete

Revision ID: ff3738101362
Revises: 9cc0e1471c1c
Create Date: 2024-11-29 01:29:30.916708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff3738101362'
down_revision: Union[str, None] = '9cc0e1471c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatrooms', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chatrooms', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('chatrooms', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'timestamp')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('messages', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('chatrooms', 'deleted_at')
    op.drop_column('chatrooms', 'updated_at')
    op.drop_column('chatrooms', 'created_at')
    # ### end Alembic commands ###
